### ISSUE TITLE
Ready SVG map doesn't work properly

### ISSUE THREAD

**Issue by RockyRock777** [okviz/SynopticPanel#11]
Hello! There is a problem with my svg map. The map works (visualization) but it doesn't show area names. 
Is SynopticPanel compatible with other languages except ENG?

[TEST.zip](https://github.com/okviz/SynopticPanel/files/1911943/TEST.zip)

Maybe i do smth wrong? I use PBI Desktop

Edited: I used SVG editor and noticed that all elements were grouped together. So i ungrouped them and now i can see area names but there is no link with my data source. SVG map and data source have the same areas.

**Comment by danieleperilli** [comment]
I checked your file, you have to change the label colors to show the labels.
![power_bi](https://user-images.githubusercontent.com/9072177/38978250-1d9aab3a-43b7-11e8-842f-3dbeff163a14.jpg)

**Comment by RockyRock777** [comment]
> I checked your file, you have to change the label colors to show the labels.

I guess you didn't understand me. The problem is that i can't link my data source with the map.

**Comment by danieleperilli** [comment]
The two labels visible means you are able to bind some data. I suggest you to open the map in a code editor and verify all data are set correctly.
