### ISSUE TITLE
Didn't show "Select Map"

### ISSUE THREAD

**Issue by WenlinZhu** [okviz/SynopticPanel#12]
When the datasheet was imported, as the map had been created in svg file, there was no display "Select Map' or "Gallary" in the Power bi.

**Comment by danieleperilli** [comment]
Please, test the latest beta version (v1.5.0). **If the issue is still present, please send us a repro file**.

**Comment by TJ-1** [comment]
I am having the same problem and I have tried "1.5.0.0.pbiviz" and "synopticPanelByOKViz-1.5.0B.pbiviz".
