### ISSUE TITLE
PowerBI to PowerPoint

### ISSUE THREAD

**Issue by FrancescoN93** [okviz/SynopticPanel#13]
Hello,
I have an issue regarding SynopticPanel on PowerBI..
I've found this visual in the list of the "List of custom visuals that have been certified", so it should be possible to export it in PowerPoint.
Anyway it is not possible, and each time i try to export it then i don't see the visual anymore.
Is there any way to fix this issue?
Thanks in advance for the support.

Francesco

**Comment by danieleperilli** [comment]
We don't have any control on custom visual certification, sorry. 
I suggest you to report the issue directly to pbicvsupport@microsoft.com (direct support for custom visuals).
