### ISSUE TITLE
Embedded map display doesn't refresh using slider

### ISSUE THREAD

**Issue by aperrott** [okviz/SynopticPanel#16]
I am using the current versions of PBI and SynopticPanel. I have several maps, stored in a table as ZIPs and embedded in the panel as described in the blog instructions. I have a PBI splitter to select the map to display. However, the displayed map doesn't always update - if I force a refresh by changing page and back for example then it displays the correct map, but if I just select a new map from the splitter control then the map doesn't refresh.
![capture](https://user-images.githubusercontent.com/36766082/40227375-4046d894-5a86-11e8-8147-fbd1d4b92893.JPG)

**Comment by aperrott** [comment]
Sorry, just to be clear - version is 1.5.0.0 downloaded from the PBI marketplace

**Comment by aperrott** [comment]
I have also now tried the 1.5.0 BETA from the website but it has the same fault unfortunately :-(

**Comment by aperrott** [comment]
I have now uploaded my maps to Github instead and this appears to work - the displayed map is updated when I select it in the splitter. So I have a workaround for now, but the original problem with embedded maps still exists.

**Comment by danieleperilli** [comment]
Please, send us the report file and the map as separated files.

**Comment by aperrott** [comment]
The PBIX file is too big (30MB) to upload and also contains confidential data
