### ISSUE TITLE
Dependent libraries are not included

### ISSUE THREAD

**Issue by choiie** [okviz/SynopticPanel#2]
There are several files defined in the tsconfig.json that are not available in the repository - would it be possible to share any of these files as open source? I'm looking to build a custom visual with some concepts from the SynopticPanel, but a lot of functions in the source files are defined in these external libraries.

These are the files in question:

    "../libraries/colorPalette.ts",

    "../libraries/objectEnumerationUtility.ts",

    "../libraries/textUtility.ts",

    "../libraries/legendUtility.ts",

    "../libraries/okvizUtility.ts",

    "../libraries/colorblind.ts"

**Comment by danieleperilli** [comment]
Take a look in the other OKViz repositories.

**Comment by choiie** [comment]
@danieleperilli Sorry, it didn't show up in "popular repositories" so I missed it. Cheers
