### ISSUE TITLE
Tooltip in polygons with same ID not work 

### ISSUE THREAD

**Issue by luisgonzalezgarcia** [okviz/SynopticPanel#20]
Hello,
First of all, congratulate yourself for your Synoptic Panel tool and the editor, fantastic work. Thank you.

I'll explain the problem. I have a map of Spain linked to the data by the province code, 08 Barcelona, ​​28 Madrid ... etc.
Everything works perfect, the provinces are colored acc
[SampleToOkviz.zip](https://github.com/okviz/SynopticPanel/files/2200860/SampleToOkviz.zip)

ording to the data, the labels look good, everything is perfect.
The problem arises with the tooltips (information on tools in PBI).
With the provinces that are a single polygon there is no problem, but the provinces that are more than one polygon only appear the province code, the rest of the data (sales, units, ...) do not appear, which do appear in the provinces of a single polygon. This is the case of the Balearic Islands (Mallorca, Ibiza, Menorca, Formetera) which are four polygons with the same ID. It also happens with the Canary Islands.

Sample file attached.

Thank you for your attention and many thanks for your work.

Regards,

Luis González

**Comment by danieleperilli** [comment]
At the moment, Synoptic Panel doesn't support multiple areas with the same ID.

**Comment by luisgonzalezgarcia** [comment]
The problem is only with the tooltips (information on tools in PBI). 
In Synoptic Designer I can create different areas with the same ID and work correctly in Synoptic Panel.

**Comment by danieleperilli** [comment]
I understand, but it is a collateral effect of some part of the code. It is not intentional and not supported (at the moment).
