### ISSUE TITLE
Alternate Software to Synoptic Designer

### ISSUE THREAD

**Issue by PeacefulCoder** [okviz/SynopticPanel#22]
Hello,

We have been using the synoptic designer and synoptic panel for more than a year. The synoptic panel tool is very useful and great for construction progress reporting.

Our issue is since we have more than 100 items to define, the website "**synoptic.design**" is not very useful for us to draw custom areas.

If you could advise us any other software that we can produce **SVG** files that could work with synoptic panel we will be grateful.

Thank you again
Regards,

**Comment by danieleperilli** [comment]
You can use Inkscape. https://okviz.com/blog/introducing-synoptic-panel-v1-4/

**Comment by PeacefulCoder** [comment]
Thank you so much for your quick reply

Regards,
