### ISSUE TITLE
SVG seen in full black

### ISSUE THREAD

**Issue by deadmouse** [okviz/SynopticPanel#25]
I have my custom SVG which is colorful, even though, when I add it to Power BI with Synoptic Panel, I see it full black color, why?

**SVG in Firefox**:

![SVG in Firefox](https://i.imgur.com/MAV5RKl.png)

**SVG in Power BI with Synoptic Panel**:

![SVG in Power BI with Synoptic Panel](https://i.imgur.com/TJJZAV4.png)

**Comment by danieleperilli** [comment]
Probably you set a not-excluded top level area that is not matched. Try to edit the file and to hide the not-matched areas in the visual options.
