### ISSUE TITLE
About display of Data Value

### ISSUE THREAD

**Issue by TomokiS** [okviz/SynopticPanel#26]
Hi, I'm trying to create a seating map with Synoptic Panel.
If I select [Data value] at Display in DataLabels, the Display is not line breaks.
But when I select [Column and value] is to display line breaks.
Is it possible to display line breaks when selecting [Data Value]?
![sample](https://user-images.githubusercontent.com/42950070/45004990-75482e80-afe0-11e8-8d61-2d9d7b3f5763.jpg)

Excel cell values of the original data are as follows.
· ["Ito" & Char (10) & "100035"]
· [yamada
    100036]
· ["suzuki" & ""  & "100037"]

Best Regards

**Comment by danieleperilli** [comment]
You can use the Word Wrap option, but you can't choose arbitrarily to insert line breaks.

**Comment by TomokiS** [comment]
Thank you for your prompt reply!!
But it can not line breaks when I use the Word Wrap option and select the Data value.

![sample](https://user-images.githubusercontent.com/42950070/45062298-c2d3a280-b097-11e8-8ebb-27f378b72ba4.jpg)

**Comment by danieleperilli** [comment]
Yes, you can't use the word wrap on Data value because it is intended to be a numeric value. In the future we could improve this behavior. Thanks for reporting!

**Comment by TomokiS** [comment]
Thank you for your reply.
I am very much looking forward for improvement!!
