### ISSUE TITLE
SynopticPanel issue with dynamic svg file URL-based

### ISSUE THREAD

**Issue by BenDecost** [okviz/SynopticPanel#27]
Dear Support,
I’m contacting you about about a notification using « Synoptic Panel » PBI visual and need some help about this topic

Power BI : Version : 2.61.5192.601 64-bit – Update Aug.2018
Power BI visual : synopticPanelByOKViz.1.5.0.0.pbiviz

We have followed the documentation about how to created svg files.
Svg file are working perfectly when we load them from local svg file.

Because we will need to change svg file Inside the visual when changing of customers, we want to use dynamic URL instead of loading locally.
We create svg files dynamically from our webservices to generate images on the fly.  This way doesn’t allow us to use the Synoptic designer tool.

Power BI parameters are : 
![image](https://user-images.githubusercontent.com/39468668/45091020-76c54400-b111-11e8-83f9-0e0564514950.png)

 

To do so, here is the notification on the visual : 
 
![image](https://user-images.githubusercontent.com/39468668/45091035-7fb61580-b111-11e8-8784-e8ead0348450.png)

We have tried many configurations in our side, read your documentations, compare with some other maps visuals - ☹ without results.
Therefore this email. Can you help us to solve this topic ?
Or is there other way to create svg file ?

Attached - please find a scipt of a svg file created by our webservice.  Is there Something wrong ?

Thank you in advance for your help.

[OKVIZ_SVG FILE.txt](https://github.com/okviz/SynopticPanel/files/2352587/OKVIZ_SVG.FILE.txt)

**Comment by danieleperilli** [comment]
Can you post an example of URL?
The URL of the image must ends with .svg.

**Comment by BenDecost** [comment]
Indeed, the " ." [dot] was missing before the file extension -> .svg
As simple as that.
Thanks for your contribution.  It works perfectly
