### ISSUE TITLE
Updating Tooltips

### ISSUE THREAD

**Issue by JBQualisteo** [okviz/SynopticPanel#28]
Hi there,

I'm a big fan of your synoptic panels. I don't know if you've noticed they've recently improved the tooltips to allow graphs as well as numerical values to appear when you scroll above any standard visual.
I was wondering if you planned on making an update to allow this new functionality which I believe would drastically improve the overall layout for most users.

Keep up the good work !

**Comment by danieleperilli** [comment]
Yes, we are evaluating several updates and the Custom Tooltips are in our backlog. Unfortunately, I can't say when the update will be released due to some external factors.
