### ISSUE TITLE
okvizUtility.isValidURL function fails for urls like https://mydevice24/foo.svg

### ISSUE THREAD

**Issue by senthilvelg** [okviz/SynopticPanel#3]
The synoptic panel control doesn't work when the url for maps is in certain format.

e.g. https://mydevice24/foo.svg

This is still a valid url for teams using an internal private server for hosting their svg maps. Fixing the regex in isValidURL function to support the above mentioned url format will be very helpful.

**Comment by okviz** [comment]
Private URLs will not work anyway with Power BI Service, so we disabled. You have to host maps on a public server. For example you can use GitHub: http://okviz.com/blog/hosting-synoptic-panel-maps-on-github/

**Comment by senthilvelg** [comment]
Thanks for the message. I tested it out with my custom power bi control and
works fine. So I'm not sure why it wont work. Also I do not want to host my
maps on public urls including GitHub due to security and prevention of IP.

**Comment by okviz** [comment]
Strange. It all our past tests it didn't worked. We will test again for the next version an,d in the case, we will remove the limitation.

**Comment by okviz** [comment]
We just included a fix in the v1.4.6.

**Comment by senthilvelg** [comment]
Thanks for the update and fixing it quickly. I will try it out sometime
this week and will let you know.
