### ISSUE TITLE
Cannot upload from local maps in synoptic panel after Power BI September update

### ISSUE THREAD

**Issue by mfaristyo** [okviz/SynopticPanel#31]
Hi,

Synoptic panel has been really great feature for me, but i found an issue which i couldnt upload my image from local maps (like i used to do it frequently before) after Power BI September update. I had been trying to use either power bi service and desktop and also used the svg from the past report with no succeed. Please advise. Thanks

**Comment by danieleperilli** [comment]
Please, provide a repro file. It works as usual, for me.

**Comment by danieleperilli** [comment]
You can't load PNGs in Synoptic Panel. PNGs are bitmap and there is no information about areas inside them. You have to convert PNGs in SVGs by using Synoptic Designer or any other graphic editor.
