### ISSUE TITLE
Synoptic  panel refuses to bind data

### ISSUE THREAD

**Issue by DavidNightSA** [okviz/SynopticPanel#36]
data not binding, no matter what I try

**Comment by danieleperilli** [comment]
You can't offer any support without additional details (aka we need the report file and the map to just). Have you read and follow the instruction on this page? https://okviz.com/blog/introducing-synoptic-panel-v1-4/

**Comment by DavidNightSA** [comment]
I cant upload the file – I tried

 

 

David Nightingale

Haute Performance

+27 61 731 8089

 <mailto:dn@hauteperf.co.za> dn@hauteperf.co.za

 <http://www.hauteperf.co.za/> http://www.hauteperf.co.za

**Comment by danieleperilli** [comment]
Just don't reply to the email notification.

**Comment by danieleperilli** [comment]
You send us the file via email. 
The issue is in your SVG file. The areas are nested inside a layer with an ID.

**Comment by DavidNightSA** [comment]
how do i get rid of that
this dinky little tool https://synoptic.design/  has like zero functionality

**Comment by danieleperilli** [comment]
Use any graphic editor, or just use the notepad. The vector images are XML.
