### ISSUE TITLE
I can´t upload an image already created

### ISSUE THREAD

**Issue by Adriano-GC** [okviz/SynopticPanel#41]
I create custom areas at my image on Synoptic Design but when a use the synoptics panel visual on power bi desktop, the button "local maps" did not appear. How can I fix it?

![capturar](https://user-images.githubusercontent.com/45639186/49539559-087d5280-f8b5-11e8-9b1a-8baf5ffa57f4.JPG)

**Comment by danieleperilli** [comment]
You must bind some data to the visual before loading map/editing properties.
