### ISSUE TITLE
Can't control which fields to appear in tooltip

### ISSUE THREAD

**Issue by EmadRadwan** [okviz/SynopticPanel#45]
Hi,

Is there a way to control those fields to appear in the tooltip? I noticed that fields used in 'category'  and 'States' also appear in tooltip which may not be desirable. Is there a way to disable this default behavior and tooltip to be dependent on  fields dragged in its section only. Thanks.

**Comment by okviz** [comment]
Sorry, at the moment is not possible to customize tooltips. We will include it in a future version.
