### ISSUE TITLE
Ability to display html5 content in a tooltip window

### ISSUE THREAD

**Issue by D1M** [okviz/SynopticPanel#5]
Hi, it would be nice to have an ability to display html5 content in a tooltip window e.g. display base64 encoded photo in tooltip window or image/url. 

Also, it would be nice to hide category or subcategory in tooltip widow - right now you can't hide one of them.

**Comment by danieleperilli** [comment]
When the new tooltips features will be available for custom visuals, we will include in Synoptic Panel.
