### ISSUE TITLE
Support <path/> or <g/> with <path/> svg tags

### ISSUE THREAD

**Issue by D1M** [okviz/SynopticPanel#6]
Today only <polygon id="XXX"/> svg tag is supported. Could you please also add a possibility to choose which tag to use to display data.
E.g. 
<g id="XXX">
<path d="M401.125,420.951c0-3.815-3.092-6.908-6.907-6.908s-6.908,3.0936.908,6.908s3.093,6.908,6.908,6.908S401.125,424.766,401.125,420.951L401.125,420.951z"/>
</g>

**Comment by danieleperilli** [comment]
Sorry, it is not possible.
