### ISSUE TITLE
too many values

### ISSUE THREAD

**Issue by djouallah** [okviz/SynopticPanel#7]
my original data was 576 rows and everything was perfect, i just added another 30 and got this message too many values, can we please increase the number of values.

**Comment by danieleperilli** [comment]
The limit is set by Power BI itself, we can’t do anything to change it, sorry.

**Comment by djouallah** [comment]
I sent you by email my private pbix, the data is 2931 and 1 category, thanks for your help

**Comment by danieleperilli** [comment]
If you try to setup your data with a built-in Matrix, you see the same error (set plant on Rows and tracker_id on Columns).
Unfortunately, Synoptic Panel doesn't support yet **incremental loading**, that should solve your issue. We will include it in one o the next update, later this year.

**Comment by djouallah** [comment]
thanks for your reply, much appreciate it.
