### ISSUE TITLE
Background not being displayed in PowerBi

### ISSUE THREAD

**Issue by nassaf** [okviz/SynopticPanel#9]
I have a Synoptic SVG background that was working and now doesn’t. It just shows the names not the floor diagram, that is the background. If I drag the SVG into Synoptic website it shows up properly. But when I add it back to PowerBi it only shows the names, not the background picture. Any idea on how to resolve this?

**Comment by danieleperilli** [comment]
Please, provide a repro to support@okviz.com (for Synoptic Panel we need a the report and the map as separated files).

**Comment by d4aus** [comment]
I'm having the same issue. SVG renders correctly in a browser or InkScape / Synoptic Designer but drops the background image in Power BI
![crr error](https://user-images.githubusercontent.com/33332066/38114673-9aa12378-33ec-11e8-9467-e636fdb46213.PNG)
. Files sent to support@okviz.com

**Comment by danieleperilli** [comment]
Solved in the v1.5.0. Thanks for reporting it!
